version: "3.4"

services:
  publisher:
    build: ../containers/publisher
    environment:
      - SUBSCRIBER_CHANNEL=aeron:udp?endpoint=172.16.0.2:10000
      - SUBSCRIBER_STREAM_ID=1
    networks:
      aeron_network:
        ipv4_address: 172.16.0.4

  subscriber:
    build: ../containers/subscriber
    environment:
      - SUBSCRIBER_CHANNEL=aeron:udp?endpoint=172.16.0.2:10000
      - SUBSCRIBER_STREAM_ID=1
    networks:
      aeron_network:
        ipv4_address: 172.16.0.2

networks:
  aeron_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

