version: "3.4"

services:
  publisher:
    build: ../containers/publisher
    environment:
      - SUBSCRIBER_CHANNEL=aeron:udp?endpoint=239.9.9.1:10000
      - SUBSCRIBER_STREAM_ID=1
    network_mode: host

  subscriber1:
    build: ../containers/subscriber
    environment:
      - SUBSCRIBER_CHANNEL=aeron:udp?endpoint=239.9.9.1:10000
      - SUBSCRIBER_STREAM_ID=1
    network_mode: host

  subscriber2:
    build: ../containers/subscriber
    environment:
      - SUBSCRIBER_CHANNEL=aeron:udp?endpoint=239.9.9.1:10000
      - SUBSCRIBER_STREAM_ID=1
    network_mode: host

